application:
  max-allowed-books: 2
  server:
    error:
      include-stacktrace: never
      include-message: always
      include-binding-errors: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jpa
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto:update
    show-sql: true